### ISSUE TITLE
version of nodeJS no longer supported

### ISSUE THREAD

**Issue by jonniepanda** [bmalnad/s3-pgp-encryptor#2]
Hi Dan,

I was looking to try out your function to pgp encrypt files dropped in an S3 bucket "automajically" but when I try to deploy it, it fails, seemingly due to an old runtime being specified. Hopefully its just change to the version number of the runtime. I have no idea how to update the files on here or even if I'm allowed to.

Any chance up updating this?

Thanks in advance.

Jonnie

**Comment by bmalnad** [comment]
I'm finally getting around to updating this today.

**Comment by jonniepanda** [comment]
Thanks Dan, I'll give it a whirl
